spring:
  http:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB
azure:
  storage:
    accountName: uploadedexcels
    container-name: excels
    connection-string: BlobEndpoint=https://uploadedexcels.blob.core.windows.net/excels?sp=racwdl&st=2023-10-05T10:39:46Z&se=2073-10-04T18:39:46Z&spr=https&sv=2022-11-02&sr=c&sig=bpSR9YGXzs2thPfFjf2P9WERAGIyz1nyEuZi3fHFc%2B0%3D
                       