spring:
  http:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB
azure:
  storage:
    accountName: uploadedexcels
    container-name: excels
    connection-string: BlobEndpoint=https://uploadedexcels.blob.core.windows.net/excels?sp=racwdl&st=2022-10-10T11:31:11Z&se=2023-04-29T19:31:11Z&spr=https&sv=2021-06-08&sr=c&sig=RNS3muH9OvrQKltofyzk%2BbGqe0eYFFqcDwavkl3A1Hk%3D