spring:
  http:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB
azure:
  storage:
    accountName: uploadedexcels
    container-name: excels
    connection-string: BlobEndpoint=https://uploadedexcels.blob.core.windows.net/excels?sp=racwdl&st=2023-10-05T16:29:05Z&se=2073-10-06T00:29:05Z&spr=https&sv=2022-11-02&sr=c&sig=5hZmpedn8%2BIikZ4EXpswZE7ijvXij5%2Fw2iZvRKX3E9o%3D