spring:
  http:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB
azure:
  storage:
    accountName: uploadedexcels
    container-name: excels
    connection-string: BlobEndpoint=https://uploadedexcels.blob.core.windows.net/excels?sp=racwdl&st=2023-05-03T12:57:15Z&se=2023-10-02T20:57:15Z&spr=https&sv=2022-11-02&sr=c&sig=4BkBKpsL2tA32HKwHap1NozxKf4ndzH72cZ67cfDlzE%3D